name: Test

on:
  push:
    branches:
    - master
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  test:
    strategy:
      matrix:
        go-version:
        - 1.15.x
        - 1.16.x
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.37
    - name: Test
      run: go test -v -count 1 -coverprofile coverage.out ./...
    - name: Coverage
      uses: jandelgado/gcov2lcov-action@v1.0.8
      if: "matrix.os == 'ubuntu-latest'"
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov
      if: "matrix.os == 'ubuntu-latest'"
